arm_task:
  arm_container:
    image: ubuntu:latest
  script: |
    apt-get -yy update
    apt-get install -yy git pandoc cmake qt6-default libnetpbm10-dev libhdf5-dev libfftw3-dev python-dev libhdf4-dev  g++ build-essential libtiff5-dev libgsl-dev lsb-release libcfitsio-dev libhdf4-dev libhdf5-dev libhdf5-100 opencl-clhpp-headers libclfft2 libclc-dev opencl-c-headers ocl-icd-libopencl1  libclc-dev beignet opencl-headers ocl-icd-opencl-dev libclfft-dev
    apt-cache search qt6 > out.txt
  artifacts:
    path: "out.txt"


# MacIntel_task:
#   macos_instance:
#     image: big-sur-base
#   script: |
#     brew update
#     brew install gcc qt cmake
#     mkdir -p build && cd build
#     cmake -DCMAKE_CXX_COMPILER=g++-12 ..
#     make || zip -r ../zipped.zip *
#   artifacts:
#     path: "zipped.zip"
     
# M1_task:
#   macos_instance:
#     image: ghcr.io/cirruslabs/macos-monterey-base:latest
#   script: |
#     brew update
#     brew install gcc qt cmake
#     mkdir -p build && cd build
#     cmake -DCMAKE_CXX_COMPILER=g++-12 ..
#     make || zip -r ../zipped.zip *
#   artifacts:
#     path: "zipped.zip"
    
